Select * from customer limit 20

-- Ques 1
-- what is the total revernue generated by male vs female
Select gender, SUM(purchase_amount) as revenue
From customer
group by gender

--  Q2 which customer used dicount but still spent more then average purchase amount 
Select customer_id, purchase_amount
From customer
where discount_applied = 'Yes' and purchase_amount >= (Select AVG(purchase_Amount) from customer)

-- Q3 which are the top 5 products with the highest rating 

Select item_purchased, ROUND(avg(review_rating :: numeric),2) as "Average Product Rating"
From customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Q4 Comapre the average Purchase amount between standard and express shipping 

Select ROUND(avg(purchase_amount),2) , shipping_type
From customer
where shipping_type in ('Standard' , 'Express')
group by shipping_type

-- Q5 Do subscribed customer spend more ? Compare avg spend and total revenue
Select subscription_status,
Count (customer_id) as total_customer,
ROUND(avg(purchase_amount),2) as average_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by average_spend, total_revenue desc

--Q6 which 5 porducts has the highest number of puchases by dicount applied
Select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 else 0 end )/ COUNT(*),2) as discount_Rate
from customer
group by item_purchased
order by discount_Rate desc
limit 5

-- Q7 segment cusotmer into new, returning and loyal based on their previous puchases
with customer_type as (
select customer_id , previous_purchases,
CASE 
  WHEN  previous_purchases = 1 THEN 'NEW'
  WHEN  previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
  else 'Loyal'
  end as customer_segment
From customer
)
select customer_segment,count(*) as "Number of customers"
from customer_type 
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;






